POINT_SIZE = 3
POINT_COLOR = "blue"

LINE_WIDTH = 2
LINE_COLOR = "green"

SEGMENT_WIDTH = LINE_WIDTH
SEGMENT_COLOR = "red"
SEGMENT_POINT_SIZE = 5
SEGMENT_POINT_COLOR = "orange"

POLYGON_WIDTH = LINE_WIDTH
POLYGON_COLOR = "purple"
POLYGON_POINT_SIZE = SEGMENT_POINT_SIZE
POLYGON_POINT_COLOR = SEGMENT_POINT_COLOR

EDGE_MATCHING_OFFSET_ABSOLUTE_MAX = 4.0
EDGE_MATCHING_OFFSET_STEP = 0.1

LINEAR_CRITERION_MAX_DISTANCE = 0.3

EDGE_DISPLACEMENTS_MIN_SHIFT = 0.01
EDGE_DISPLACEMENTS_ALPHA_BUFFER = 1.0
EDGE_COMPUTATIONS_ERROR_TOLERANCE = 1e-6
