#pragma once

#include <sys/types.h>

const double EDGE_CRITERION_MAX_DISTANCE = 0.3;
const double EDGE_CRITERION_OFFSET_MAX = 4.0;
const uint EDGE_CRITERION_REFINEMENT_SAMPLES = 2;
const double EDGE_CRITERION_FINAL_PRECISION = 0.5;

const double EDGE_CRITERION_POINT_DENSITY = 3; // Points per meter
const double EDGE_CRITERION_ALPHA_MEAN_EDGES_RATIO = 0.5;
const double EDGE_CRITERION_ALPHA_MEAN_EDGES_DIFFERENCE = 0.5;
// const double EDGE_CRITERION_ALPHA_AREA_RATIO = 0.0;
const double EDGE_CRITERION_ALPHA_PERIMETER_ABSOLUTE = 0.0;
