name: Documentation
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.6
        with:
          pixi-version: v0.70.2
          cache: true
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
          working-directory: ./docs
      - name: Build Zensical documentation
        working-directory: ./docs
        run: pixi run zensical build --clean
      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs/site
      - uses: actions/deploy-pages@v4
        id: deployment
